sudo: false
language: cpp
cache: ccache
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - libboost1.55-all-dev
        - clang-6.0
        - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="osx-g++-8"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="osx-g++-7"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"
before_install:
- eval $MATRIX_EVAL
install:
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true
  ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry
  brew upgrade llvm ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"
  ; fi
- if [[ "$LABEL" == "osx-g++-8" ]]; then travis_retry brew install gcc@8 ; fi
- if [[ "$LABEL" == "osx-g++-7" ]]; then travis_retry brew install gcc@7 ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export BASEDIR=`pwd` ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd $HOME ; fi
- if [[ "$LABEL" == "aarch64" ]]; then wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then mkdir toolchain && cd toolchain ; fi
- if [[ "$LABEL" == "aarch64" ]]; then tar xfv ../gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
  >/dev/null ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then tar zxvf ../../boost_1_55_0.tar.gz >/dev/null
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd boost_1_55_0 ; fi
- if [[ "$LABEL" == "aarch64" ]]; then ./bootstrap.sh ; fi
- if [[ "$LABEL" == "aarch64" ]]; then curl https://raw.githubusercontent.com/turtlecoin/turtlecoin/development/scripts/fix_boost_aarch64.sh
  | sh ; fi
- if [[ "$LABEL" == "aarch64" ]]; then ./b2 toolset=gcc-aarch64 --with-system --with-filesystem
  --with-thread --with-date_time --with-chrono --with-regex --with-serialization --with-program_options
  >/dev/null; fi
- if [[ "$LABEL" == "aarch64" ]]; then export CUSTOM_BOOST_ROOT="-DBOOST_ROOT=`pwd`"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export CUSTOM_TOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../scripts/cross-aarch64.cmake"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export STRIP="$HOME/toolchain/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-strip"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd $BASEDIR ; fi
script:
- eval $MATRIX_EVAL
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=true .. ${CUSTOM_TOOLCHAIN} ${CUSTOM_BOOST_ROOT}
  ${ADDITIONAL_CMAKE_ARGS}
- make -j2
before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="AmityCoind miner zedwallet amity-service zedwallet-beta cryptotest wallet-api"
- "${STRIP} ${TARGETS}"
- rm -rf amitycoin-${TRAVIS_TAG}
- mkdir amitycoin-${TRAVIS_TAG}
- cp ${TARGETS} amitycoin-${TRAVIS_TAG}/
- cp ../../LICENSE amitycoin-${TRAVIS_TAG}/
- tar cvfz amitycoin-${TRAVIS_TAG}-${LABEL}.tar.gz amitycoin-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp amitycoin-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..
deploy:
  provider: s3
  access_key_id:
    secure: BjBKgljWwPC4G00fDkj31ORsgkDf5H/MjN0oBNLlqTXIYrpdOTHdQ+SJnkWfr/HTi8G1YnQwZv5+O6Bqrl2ctVu50Mqeot5kp+9MpGlH/uBoFNFWHVSNpkC73biZIFuNKqYQMwEYld0X+mMt+izKqItmYazNIPyH5Hnxt1kTBUFRYmBcmpkywv6nljiw9NLb7zg32LSXurOb4JDaxHpSJTtKqio15495uzM84dmRXqtJa7ieoRtiAq9S4URv+FRS4ks8bh9ER9Qin4U8j8Bf4axO/dEZrjPueHIKp8wQG//V6SzuQkZzJXy4uguDpMUYEqTOsexmip/EU81gfwlU2gA9j3oszamzCYqFRiLe+OvsaKVSuG8TeuzzIPdXxg2xV4Jf0ZNwopXQR7juKr2bFP7JKZkM5P6YGyKBRIAm+WT3R+pl+offfQueO55SXswEZmUH549H70sRwFaCIQcE7Z0YEiF5hinIU1CfCp+2SVPnyh79U6TxqTtXXSBHFskYUa0dGt97yfwFnNXASnYHWsTmbGydnIr53ySK0ExgHLLa8+uJegAW4O4S1rgloOpCzTmBnablVyCwYdnJar3ijia1GWW1m4ZcTR2wmAuq0wjbgXV2SECXn8KDdIdEqN1ywDgfaS/1nmOU2a7JdTQiRAlbSLtnio+pCsCvJMipqqw=
  secret_access_key:
    secure: Lrg5hP5YhnLeDcndrfVD7m+iXGUEfDynKBTWEmIiN5u2nwmz9rX8FK9/UkGFqHN2O1qVL0Dg1u3Rvsy6vZ3KPowIYsp/0hP0CuGoe4rfnoY2FWTNySlt1Z4UOHiiMRcZ2IUj3orUmsQ7V3gzaeFhLkrG1jtYYSqrdzG4e8eH/zaYogtSqlNxttGAEzXWpg+AT+h895C3MZBQurZMfanwtkkziQ+TkpXI4vjnziJjBfbd1lePCLkm5WtjpVoA4PmsLRUjEbsXq7yVYav62QlXa/sGtGcCF/X8c2d/1bQIgDbsmeDPfsbXvM41ggOwKBmCTGUkCgJIPE+xbaJZMD3F2ZrBB+2Fr4mi7Y3LcamyS5+quUF5ogFPUKfcDbFoWUYU/nXY4J3NvfxVb52byX8YLwgJrTDdlRIKUoQbsZFfJeTHEOoKCxLDKnwcAZvz94qC1Y0PtsMKy6bz654IHqRRwzQ2L2hnBhMeujJD0fU4fKkcucCGrshLa2KloiacMzQiBVtWzZ5aIZx2WnVkzX+PeKjHPOOjVHVBkU62y5VQL0uggmB4QBUPbhjDp8cSDsoom5d2FFAQljO7TfxBtyDB7AHzoNFFaTixHFVSjkCfAIKfHnnGr4E72cNEMQ6te5oVENHIQvQQzKCkzb/ULcDTdpCwxlUW5dcLo1eqY6tiO/w=
  bucket: amitycoin1
  skip_cleanup: true
  local-dir: src/builds
  on:
    repo: CalexCore/AmityCoin
    branch: dev
env:
  global:
  - secure: uDNR7lW2QLJXfwoAE53e0Ja86xFENjSXEVztkT/PyVxnIMincFWoVxfackCokRHZOBw4DFjkQ95MsRoBC+YE7O20G5JS3pzMzd6hbIHKCsxI8Tqtnyy0J5Ff91hXOUCAG8YaOuwsbPsqo7zsNPr8mq7NRBSlSOOEbRd2Vpo6rafCmgpiU5FygvfLXxDHKyJyC+i9HjKwRm7JpK4i1ZkcSP5+NpVNKD3ohiYtWSJJLBtYD0W3gRfpZxF7ZnsiOYOF5hAH4tkaLE8FI43ZaKUJL87d59qDiog4qx57sMuSHqWje7YiaI4sw8e9c42a4cEWvkfE+E89LK71dItoGpiFCKa6wxdUvoohBmZlRuFgtnEhAC0gbrDakPJQ96Z92JIHW8coi7ZF/y/krdOYOIJcITkA6EAqJtYx4n2PrAbZJNfjCx5IgOowMB3V3UiyEsAaFGliR/iQKvJOuvXNRWalfplFAiGuKm3B/XXSeqcT5L4kgiIZhpoG9feGG/08/3Rx6rUEwayNyRTlo5cABQPMCjLEZc5aFvcUmMNn2hDF0vpqvnjaDvT1aYj1TnlyMMXbwQSh8KNHc13xj202vbiUoElvxIddglcUPjQu5eOrvkFaSKjPCR1xNxuNn4A0a1AaJbyfCFDlGh6oAu5ji4DzjVWzj5iJDMexO1IFMys9ovE=
  - secure: j5RCihzq64jdod77IkZvh1IE9wZEB+WnlPBOyPUAOhbtvkuzAFkW3lrhb6+CDTwYDaFKUQIhxudGXr3mpZD8ogFd3VSfai2wvTf3ryzH4t1tA8wNby5GjRT5y2OD73p8KKTDNwWZNj4k7VO0suShym/j4Kv9BiMbwpckOGNAVX8TbTMivwWpr6Yc9557PYPPPe2App0TTLYRY2Unm6Igwtoqu9n+dJj6MEvmzddimV7+lm23LoVNyi9JFnPEx7iTXK1pPtrdcziPZjOxOLbn7+iSsISjZHFMtmj5aZK95L36PO9qHth88GdG4/zpQLMAqki0G1z5DBEL7A8/U3bQBlE/iE+t06Aeeg0rMMZfbW9wYnGrH8knT41UShKoq7myq8Tw04rDeKmELJ8+YVYmm8YTnDfU1nyS/t3wxlbHeIREakQsU8o+CBpgntbYZ2hwJExoB4qMsCwSRHVbyDz/qkixWLIdvjrQcKzZr6ZhNocnSImznmkT/KBw0VoboE5E5XHZXpNtMmIFaHAzmQMlMHFu7XRAdUBdcmRGpr5LSKEYlBqBDjRrz37yLFV5meBGOm6+r72mXJjQ15nQ2SpSXElPZXX75UFKbABw8+EPWkKfyztcnsFhhIGUJUcRjORUG2O4ll2QeHHk/myabIAT85+R4L9Trl90EERWRYGuR2U=
