sudo: required

language: cpp

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - VERSION=`cat VERSION`
  - echo "Building v$VERSION on branch $TRAVIS_BRANCH"
  - |
    docker build \
      -t chrischaos/amitycoin:$TRAVIS_BRANCH-$VERSION \
      -t chrischaos/amitycoin:$TRAVIS_BRANCH-latest \
      .
    docker push chrischaos/amitycoin:$TRAVIS_BRANCH-$VERSION
    docker push chrischaos/amitycoin:$TRAVIS_BRANCH-latest
  - |
    if [ "$TRAVIS_BRANCH" == "docker-hub" ]
    then
      docker tag chrischaos/amitycoin:$TRAVIS_BRANCH-$VERSION chrischaos/amitycoin:latest
      docker push chrischaos/amitycoin:latest
    fi
branches:
  only:
    - docker-hub
