image:
  - Visual Studio 2017
  - Ubuntu

configuration:
  - Release

platform:
  - x64

cache:
  - .build

install:
  - sh: |
      sudo apt-get update
      sudo apt-get install -y libboost-all-dev

before_build:
  - git submodule update --init --recursive

build_script:
  # setup c++ environment on windows
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  # select cmake generator and boost version
  - ps: |
      if ($isLinux) {
        $CMakeGenerator = "Unix Makefiles"
        $CMakeBoostArg = ""
      } else {
        $CMakeGenerator = "Visual Studio 15 2017 Win64"
        $CMakeBoostArg = "-DBOOST_ROOT=C:/Libraries/boost_1_67_0"
      }

  # build process
  - ps: |
      New-Item -ItemType Directory -Force -Path .\.build  | Push-Location
      cmake `
        -G "$CMakeGenerator" `
        -DCMAKE_BUILD_TYPE=$configuration `
        -DCMAKE_INSTALL_PREFIX:PATH=../.install `
        -DAMITY_BUILD_CRYPTOTEST=ON `
        $CMakeBoostArg `
        ..
      cmake --build . --config $configuration
      cmake --build . --target install --config $configuration
      Pop-Location

  # settings environment for proper artifact naming
  - ps: |
      if ($isLinux) {
        $env:ArtifactOS = "Debian 64bit"
      } else {
        $env:ArtifactOS = "Windows 64bit"
      }
    
# Tests
# Currently the only test cryptotest will always fail and noone investigated so far
# thus its left out.

artifacts:
  - path: .install
    name: "Portable Binaries ($($env:ArtifactOS))"

# deploy: !TODO