image:
  - Visual Studio 2017
  - Ubuntu

configuration:
  - Release

platform:
  - x64

install:
  - sh: |
      sudo apt-get update
      sudo apt-get install -y libboost-all-dev

before_build:
  - git submodule update --init --recursive

build_script:
  # setup c++ environment on windows
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  # select cmake generator and boost version
  - ps: |
      if ($isLinux) {
        $CMakeGenerator = "Unix Makefiles"
        $CMakeBoostArg = ""
      } else {
        $CMakeGenerator = "Visual Studio 15 2017 Win64"
        $CMakeBoostArg = "-DBOOST_ROOT=C:/Libraries/boost_1_67_0"
      }

  # build process
  - ps: |
      New-Item -ItemType Directory -Force -Path .\.build  | Push-Location
      cmake `
        -G "$CMakeGenerator" `
        -DCMAKE_BUILD_TYPE=$configuration `
        -DCMAKE_INSTALL_PREFIX:PATH=../.install `
        -DAMITY_BUILD_CRYPTOTEST=ON `
        $CMakeBoostArg `
        ..
      cmake --build . --config $configuration
      cmake --build . --target install --config $configuration
      Pop-Location

  # settings environment for proper artifact naming
  - ps: |
      $env:AmityVersion = Get-Content -Path ./VERSION
      if (-Not $env:APPVEYOR_REPO_BRANCH -match "master") {
        $env:AmityVersion = "$($env:AmityVersion)~$($env:APPVEYOR_REPO_BRANCH)"
      }
      Rename-Item -Path ./.install/bin -NewName "Amity-v$($env:AmityVersion)"
      if ($isLinux) {
        $env:ArtifactOS = "Debian 64bit"
      } else {
        $env:ArtifactOS = "Windows 64bit"
      }
    
# Tests
# Currently the only test cryptotest will always fail and noone investigated so far
# thus its left out.

# Uploading artifacts
artifacts:
  - path: .install
    name: "Standalone $(ArtifactOS) - v$(AmityVersion)"

# If we are on master branch and have a tagged version we create a new draft
# on github release. The draft must be revisioned and published by an authorized
# member of the project.
deploy:
  tag: $(AmityVersion)
  release: Amity-v$(AmityVersion)
  description: 'CI Release Build'
  provider: GitHub
  auth_token:
    secure: Pw4T3cHP71ABVKp/ZijUFxpsEvh6VlGP1eeWzCsFVnMdzEG3V7wGFcw2PyF+JXuY
  draft: true
  prerelease: false
  on:
    branch: master

notifications:
  - provider: Email
    to:
      - michael.herwig@hotmail.de
    on_build_success: false
    on_build_failure: true
